import pandas as pd

HIGH_RISK_COUNTRIES = {
    "Iran", "North Korea", "Syria", "Russia", "Myanmar", "Afghanistan"
}

def apply_aml_rules(df: pd.DataFrame) -> pd.DataFrame:
    """
    Evaluates transaction characteristics against standard money laundering typologies.
    Returns the dataframe with rule indicators and rule trigger count columns.
    """
    df = df.copy()

    # Safety check for empty dataframe
    if len(df) == 0:
        rule_cols = [
            "rule_high_value", "rule_unusual_amount", "rule_high_velocity",
            "rule_structuring", "rule_high_total_sender_value", "rule_high_risk_country"
        ]
        for col in rule_cols:
            df[col] = False
        df["rules_triggered"] = 0
        return df

    # Benchmarks for high-value and high-frequency outliers
    amount_95 = df["amount"].quantile(0.95)
    amount_99 = df["amount"].quantile(0.99)
    # Fallback to defaults if NaN (e.g. single transaction or empty column)
    amount_99 = 10000 if pd.isna(amount_99) else amount_99

    # Sender aggregated statistics
    sender_txn_count = df.groupby("sender")["amount"].transform("count")
    sender_total_amount = df.groupby("sender")["amount"].transform("sum")
    sender_avg_amount = df.groupby("sender")["amount"].transform("mean")

    # High Velocity Threshold (95th percentile of transaction frequencies)
    freq_95 = sender_txn_count.quantile(0.95)
    freq_95 = 5 if pd.isna(freq_95) or freq_95 < 2 else freq_95

    # Total Sender Value Threshold (95th percentile of total volume)
    vol_95 = sender_total_amount.quantile(0.95)
    vol_95 = 50000 if pd.isna(vol_95) else vol_95

    # Rule 1: High-value transaction (exceeds 99th percentile)
    df["rule_high_value"] = df["amount"] >= amount_99

    # Rule 2: Unusual amount relative to average transaction value (3x larger)
    df["rule_unusual_amount"] = (df["amount"] > (sender_avg_amount * 3)) & (sender_txn_count > 1)

    # Rule 3: High transaction velocity (transaction count exceeds 95th percentile)
    df["rule_high_velocity"] = sender_txn_count >= freq_95

    # Rule 4: Structuring (amounts intentionally placed just under the $10,000 reporting threshold)
    df["rule_structuring"] = (df["amount"] >= 9000) & (df["amount"] < 10000)

    # Rule 5: High total transaction value generated by a single sender (exceeds 95th percentile)
    df["rule_high_total_sender_value"] = sender_total_amount >= vol_95

    # Rule 6: Transaction involves a high-risk country
    df["rule_high_risk_country"] = (
        df["sender_country"].fillna("").astype(str).str.strip().isin(HIGH_RISK_COUNTRIES) |
        df["receiver_country"].fillna("").astype(str).str.strip().isin(HIGH_RISK_COUNTRIES)
    )

    rule_cols = [
        "rule_high_value",
        "rule_unusual_amount",
        "rule_high_velocity",
        "rule_structuring",
        "rule_high_total_sender_value",
        "rule_high_risk_country",
    ]

    # Calculate sum of rule violations per transaction
    df["rules_triggered"] = df[rule_cols].sum(axis=1)

    return df
